language: python
env:
  - TOXENV=flake8
  - TOXENV=docs
  - TOXENV=py36
  - TOXENV=unittest
install: 
  - pip install -r requirements_tests.txt
  - pip install -r requirements.txt
  - pip install -e .
script:
  - tox -e $TOXENV
after_success:
  - coveralls
deploy:
  secure: "kkBIwKUwNhsfuO9R/Y0hbrLe2WN7vShQnRaA6Z+jWk6tY6gSnu3WxwSxAjI4Ga634baubS+oFCG+NJHvZWnrTS+FjnO2bSOYByG7JA4iLnpBwULTFhZRWYr1WYUoLuVWppu9jYdDv0SOAo9w1+9e3sAfT3YIP64vYcRHZoDtWgS82AHsTRbBOYguKUPLtxvTWqNA96JkyvU/z4pLwOvxnh/0WS5S22EkI2yJ4k9lmHlpGKQAjxZyKd+yt1rWPDOK/cP4LFW13BGskvR2E00qgjyOGUbu0jSy7HJ4WpvpwZ7xvznvTsFHaRMvHzUzIyr5HCF8lVAVuws7rH2Iv0k1bHTrVQDF+O+iQCQ7JGHFzPXHFjWVZg7ZzwszmiIBCD0OyC+3zoQm9CXuRXw35h9Bl3gDGjPH3IexWZ83KYpaNyrrvrEw0PaM8R1lzu9w+M/SztTYySQxYHHv1a+peI+33a59Phzd5Tyv4eQgEB7I8C8tdn1k8jbRTpSxP9EGKCZRnAnD0ggf13/PZpDDwCMlVXr7NH2JHxh94Sw5jgXQXZakc8P/T9V+H7uBhPpotNZVe00YAiBxhAuTL344PF0VDGCu3lsEF40l2dChhcwKwHplVAdyhvXgmll70Z1qZkJqasJ5+t2UsAPUJnceH0gQO3iS00ITsmSK/HfHjMIr2xA="
